/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantasvszombies.Interface;

/**
 *
 * @author marco_000
 */

import java.io.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import plantasvszombies.Tablero;
public class Ranking extends javax.swing.JFrame {
    
    private static HashMap<String, ArrayList<Integer>> baja = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> media = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> alta = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> imposible = new HashMap<String, ArrayList<Integer>>();
    
    private static String nivel;

    /**
     * Creates new form Ranking
     */
            
    public Ranking(HashMap<String, ArrayList<Integer>> baja, HashMap<String, ArrayList<Integer>> media, HashMap<String, ArrayList<Integer>> alta, HashMap<String, ArrayList<Integer>> imposible) {
        
        this.baja = baja;
        this.media = media;
        this.alta = alta;
        this.imposible = imposible;
        
        this.nivel = "BAJA";
        
        initComponents();
       
        String[] columnNames = {"Nombres","Partidas jugadas","Partidas perdidas","Partidas ganadas","Puntos"};
        
        jTable1 = new JTable(getRows(baja),columnNames);

    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ranking de los Jugadores");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BAJA", "MEDIA", "ALTA", "IMPOSIBLE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Partidas jugadas", "Partidas ganadas", "Partidas perdidas", "Puntos"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       nivel =(String)jComboBox1.getSelectedItem();
       String[] columnNames = {"Nombres","Partidas jugadas","Partidas perdidas","Partidas ganadas","Puntos"};
 
       if("BAJA".equals(nivel)){
           jTable1 = new JTable(getRows(baja),columnNames);
           jScrollPane1.setViewportView(jTable1);
       }
       
       if("MEDIA".equals(nivel)){
           jTable1 = new JTable(getRows(media),columnNames);
           jScrollPane1.setViewportView(jTable1);
       }
       
       if("ALTA".equals(nivel)){
           jTable1 = new JTable(getRows(alta),columnNames);
           jScrollPane1.setViewportView(jTable1);
       }
       
       if("IMPOSIBLE".equals(nivel)){
           jTable1 = new JTable(getRows(imposible),columnNames);
           jScrollPane1.setViewportView(jTable1);
       }
       
    }//GEN-LAST:event_jComboBox1ActionPerformed
   
    private Object[][] getRows(HashMap<String, ArrayList<Integer>> mapa){
        ArrayList<Integer> numerosAux = new ArrayList<Integer>();
        Object[][] data = new Object[5][5];
        int filas = 0;
        
        for (int i = 0; i<5 ; i++){
            for(int j = 0; j < 5; j++){
                data[i][j] = "  ";
            }
        }
        
        Iterator it = mapa.entrySet().iterator();
        while (it.hasNext() && (filas<5)) {
             
            Map.Entry pair = (Map.Entry)it.next();
            
            data[filas][0] = pair.getKey();
            numerosAux = (ArrayList<Integer>)pair.getValue();
            data[filas][1] = numerosAux.get(0);
            data[filas][2] = numerosAux.get(1);
            data[filas][3] = numerosAux.get(2);
            data[filas][4] = numerosAux.get(3);
            
            filas++;
        }
       
        return data;
    }
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
