/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantasvszombies.Interface;

import javax.swing.ImageIcon;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.concurrent.TimeUnit;
import javax.swing.*;
import plantasvszombies.CaraCubo;
import plantasvszombies.Girasol;
import plantasvszombies.LanzaGuisantes;
import plantasvszombies.Nuez;
import plantasvszombies.Personaje;
import plantasvszombies.Tablero;
import plantasvszombies.Zombie;
/**
 *
 * @author marco_000
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    private javax.swing.JLabel cesped [] []= new JLabel[7][7] ; 
    private javax.swing.JLabel lanzaGuisantes [] []= new JLabel[7][7] ; 
    private javax.swing.JLabel girasol [] []= new JLabel[7][7] ; 
    private javax.swing.JLabel zombie [] []= new JLabel[7][7] ; 
    private javax.swing.JLabel nuez [] []= new JLabel[7][7] ;
    private javax.swing.JLabel caraCubo [] []= new JLabel[7][7] ; 
    
    private static HashMap<String, ArrayList<Integer>> baja = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> media = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> alta = new HashMap<String, ArrayList<Integer>>();
    private static HashMap<String, ArrayList<Integer>> imposible = new HashMap<String, ArrayList<Integer>>();
    
    private String comando;
    private int soles;
    private int ciclo;
    private String nombre;
     
    public Ventana(int soles, int ciclo, String nombre, HashMap<String, ArrayList<Integer>> baja, HashMap<String, ArrayList<Integer>> media, HashMap<String, ArrayList<Integer>> alta, HashMap<String, ArrayList<Integer>> imposible) {
        initComponents();
        comando = null;
        this.soles = soles;
        this.ciclo = ciclo;
        this.nombre = nombre;
        
        this.media = media;
        this.alta = alta;
        this.imposible = imposible;
        this.baja = baja;
        
        jLabel2.setText(nombre);
        jLabel1.setText("Soles: "+this.soles);
        jLabel3.setText("Ciclo: "+this.ciclo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Codigo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Codigo.setText("Introduzca comando");
        Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CodigoActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Soles:");

        jLabel3.setText("Ciclo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        getImagen();
        jPanel2.setLayout(new java.awt.GridLayout(7, 7));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton2.setText("RANKING");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       comando = this.Codigo.getText();
       System.out.print(comando);
       this.Codigo.setText("");
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(evt.getSource()==jButton2){
           Ranking ran = new Ranking(baja,media,alta,imposible);
           ran.setVisible(true);
           
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodigoActionPerformed
        String comando1;
        comando1 = this.Codigo.getText();
        
    }//GEN-LAST:event_CodigoActionPerformed

    /**
     * @param args the command line arguments
     */
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeraVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }
    
    public String getComando(){
        return comando;
    }
    public void getMostrar(Personaje per,int x, int y){
        LanzaGuisantes guisantesAux = new LanzaGuisantes(0, 0, 0);
        Girasol girasolAux = new Girasol(0, 0, 0);
        Nuez nuezAux = new Nuez(0, 0, 0);
        Zombie zombieAux = new Zombie(0, 0, 0);
        CaraCubo cuboAux = new CaraCubo(0, 0, 0);
        
       
        
        if (per.getClass() == guisantesAux.getClass() ){
            cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\lanzaguisantes.jpg"));

        }
        if (per.getClass() == girasolAux.getClass() ){
            cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\girasol.jpg"));

        }
        if (per.getClass() == nuezAux.getClass() ){
            cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\nuez.jpg"));

        }
        if (per.getClass() == zombieAux.getClass() ){
            cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\zombie.jpg"));

        }
        if (per.getClass() == cuboAux.getClass() ){
            cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\caracubo.jpg"));

        }
    }
   
    public void setCesped(int x, int y){
        cesped[x][y].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\cesped.jpg"));
    }
    
    public void setComandoNull(){
        comando = null;
    }
    
    public void  getImagen (){
        
       
        int filas = 7;
        int columnas = 7;
        for (int i=0; i <filas ; i++){
            for (int c=0; c <columnas ; c++){
                cesped[i][c] = new JLabel();
                cesped[i][c].setIcon(new javax.swing.ImageIcon("C:\\Users\\marco_000\\Desktop\\Imagenes\\cesped.jpg"));
                jPanel2.add(cesped[i][c]);
            }
        }
        
    }
    public void  setSoles (int soles){
        this.soles = soles;
        jLabel1.setText("Soles: "+this.soles);
        
    }
    public void  setCiclo (int ciclo){
        this.ciclo = ciclo;
       jLabel3.setText("Ciclo: "+this.ciclo);
   }
    public void getTerminar(){
        JOptionPane.showMessageDialog(this,"Los zombies han llegado hasta el final del tablero"+"\n HAS PERDIDO LA PARTIDA!!!","Fin de la Partida",JOptionPane.INFORMATION_MESSAGE);
    }
     public void getGanar(){
        JOptionPane.showMessageDialog(this,"Has matado a todos los zombies"+"\n ENHORABUENA"+" HAS GANADO LA PARTIDA!!!","Fin de la Partida",JOptionPane.INFORMATION_MESSAGE);
    }
   public void getSinSoles(){
        JOptionPane.showMessageDialog(this,"Te has quedado sin soles","ERROR",JOptionPane.INFORMATION_MESSAGE);
    }
   public void getPosicionErronea(){
        JOptionPane.showMessageDialog(this,"Posicion indicada ya ocupada ","ERROR",JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void getColumnasErroneas(){
        JOptionPane.showMessageDialog(this,"Numero de columnas que has introducido es mayor de las que existen en el tablero","ERROR",JOptionPane.INFORMATION_MESSAGE);
    }
    public void getFilasErroneas(){
        JOptionPane.showMessageDialog(this,"Numero de filas que has introducido es mayor de las que existen en el tablero","ERROR",JOptionPane.INFORMATION_MESSAGE);
    }
     public void getAyuda(){
        JOptionPane.showMessageDialog(this,"\"G = girasoles\\n\"+\"L = lanza guisantes\\n\"+\"[][] = coordenadas  \\\"y\\\" y \\\"x\\\" posición\\n\"+ \"S = salir del juego\"","AYUDA",JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        public void run() {
//            new Ventana().setVisible(true);
        }
    }
}
